export const HOST_ADMIN_COPY = {
  title: 'Naud Tally',
  eyebrow: 'Host route',
  heading: 'Host admin',
  body: 'Manage rooms, the live drink list, and guest billing without crowding the main order-entry screen.',
  backAction: 'Back to order entry',
  flashSuccessAddRoom: 'Room added to the live room list.',
  flashSuccessRemoveRoom: 'Room removed from the live room list.',
  flashSuccessAdd: 'Drink added to the live catalog.',
  flashSuccessRestore: 'Drink restored to the live catalog.',
  flashSuccessRemove: 'Drink removed from the live order-entry catalog.',
  flashSuccessBill: 'Guest tab billed and moved out of the open list.',
  roomsTitle: 'Rooms',
  roomsBody: 'Configure the fixed room list that appears on the order-entry screen.',
  addRoomTitle: 'Add a room',
  roomNumberLabel: 'Room number',
  addRoomAction: 'Add room',
  removeRoomAction: 'Remove',
  canRemoveRoomHint: 'Ready to remove from the room list.',
  roomInUseHintPrefix: 'Still used by',
  roomInUseHintSuffix: 'open guest tabs.',
  roomsEmptyTitle: 'No rooms configured',
  roomsEmptyBody:
    'Add the first room so the host can start from a fixed room list on the order-entry screen.',
  drinksTitle: 'Drinks',
  drinksBody:
    'Add new drinks for the live catalog, or remove unused drinks before they appear in order entry.',
  addDrinkTitle: 'Add a drink',
  nameLabel: 'Drink name',
  priceLabel: 'Price in euro',
  addAction: 'Add drink',
  activeDrinksTitle: 'Active drinks',
  removedDrinksTitle: 'Removed drinks',
  removedDrinksBody: 'Removed drinks stay out of the guest flow until you restore them.',
  removeAction: 'Remove',
  restoreAction: 'Restore',
  canRemoveHint: 'Ready to remove from the guest list.',
  inUseHintPrefix: 'Still recorded on',
  inUseHintSuffix: 'open guest tabs.',
  billingTitle: 'Open guest tabs',
  billingBody: 'Review each tab and bill the guest when they leave.',
  billingAction: 'Bill guest',
  billingEmptyTitle: 'No open guest tabs',
  billingEmptyBody:
    'New or returning guests will appear here as soon as they start tallying drinks.',
  historyTitle: 'Recently billed',
  historyBody: 'Use this quick history to double-check what has already been closed out.',
  historyEmptyTitle: 'No billed guests yet',
  historyEmptyBody: 'Billed tabs will collect here after you close them from the open guest list.',
  roomLabel: 'Room',
  totalLabel: 'Current total',
  billedAtLabel: 'Billed',
  pendingLabel: 'Pending balance',
  billedLabel: 'Billed so far',
  activeRoomCountLabel: 'Configured rooms',
  activeDrinkCountLabel: 'Active drinks',
  openGuestCountLabel: 'Open guest tabs',
} as const;
