export const ORDER_ENTRY_COPY = {
  title: 'Naud Tally',
  eyebrow: 'Order entry',
  hostToolsAction: 'Host tools',
  roomLabel: 'Room',
  roomPanelEyebrow: 'Step 1',
  roomPanelTitle: 'Choose a room',
  roomPanelHint: 'Start from the fixed room list configured on the host screen.',
  roomPanelOpenGuestsLabel: 'open guests',
  roomPanelEmptyTitle: 'No rooms configured yet',
  roomPanelEmptyBody:
    'Open host tools to add the room list before taking the first order.',
  roomPanelEmptyAction: 'Open host tools',
  guestPanelEyebrow: 'Step 2',
  guestPanelTitle: 'Choose a guest',
  guestPanelHint: 'Select an open tab in the chosen room or add a new guest.',
  guestPanelNoRoomTitle: 'Choose a room first',
  guestPanelNoRoomBody: 'The guest list appears after you select a room.',
  guestPanelEmptyTitle: 'No guests in this room yet',
  guestPanelEmptyBody: 'Add the first guest for this room to start taking orders.',
  guestPanelAddAction: 'Add guest',
  guestPanelNameLabel: 'Full name',
  guestPanelSubmitAction: 'Open tab',
  guestPanelCancelAction: 'Cancel',
  orderPanelEyebrow: 'Step 3',
  orderPanelTitle: 'Record drinks',
  orderPanelHint: 'Tap the drinks the guest ordered. Use plus and minus to adjust counts.',
  orderPanelNoRoomTitle: 'Choose a room to start',
  orderPanelNoRoomBody: 'The order panel opens after you choose a room and guest.',
  orderPanelNoGuestTitle: 'Choose a guest to record drinks',
  orderPanelNoGuestBody: 'Select an existing tab or add a guest in the chosen room.',
  orderPanelTotalLabel: 'Running total',
  orderPanelCountLabel: 'Total drinks',
  orderPanelRecordedSuffix: 'recorded',
} as const;
